spring.application.name=DBStudy

# H2 ?? (???? ???? DB)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Spring Security ????
spring.security.basic.enabled=false

# SQL ??? ?? ??
spring.sql.init.schema-locations=classpath:member.sql  
spring.sql.init.mode=always
