spring.application.name=DBStudy
spring.datasource.url=jdbc:h2:tcp://localhost/~/github
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.initialize=true

spring.security.user.name=disabled
spring.security.user.password=disabl

spring.sql.init.schema-locations=classpath:member.sql
spring.sql.init.mode=always
